import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import InitialLoading from "@/components/initial-loading";
import { Suspense } from "react";
import InitialLoadingSkeleton from "@/components/initial-loading skeleton";
import StarBackground from "@/components/background";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={montserrat.className + " bg-black"}>
                {children}
                <Suspense fallback={<InitialLoadingSkeleton />}>
                    <InitialLoading />
                </Suspense>
                <StarBackground />
            </body>
        </html>
    );
}
